### ISSUE TITLE
Parser input

### ISSUE THREAD

**Issue by paolo-gajo** [SamsungLabs/Multitask-RFG#1]
Hello, I am trying to match [the paper's Fig. 2 (right)](https://i.imgur.com/XaBGL4h.png) with your implementation and I have a couple of questions.

1. After the tagger, why does your diagram say you pass the one-hotted tagger output through an MLP, although you use an Embedding layer ([line 224](https://github.com/SamsungLabs/Multitask-RFG/blob/main/mtrfg/parser/biaffine_dependency_parser.py#L224)) just like in Donatelli et al. (left in Fig. 2)?

```
tag_embeddings = self.tag_embedder(pos_tags)
```

2. Could you explain what the purpose of [lines 232-234](https://github.com/SamsungLabs/Multitask-RFG/blob/main/mtrfg/parser/biaffine_dependency_parser.py#L232) is in biaffine_dependency_parser.py:

```
head_sentinel = self._head_sentinel.expand(batch_size, 1, encoding_dim)
# Concatenate the head sentinel onto the sentence representation.
self.encoded_text = torch.cat([head_sentinel, encoded_text], 1)
```

That is, why do we need to concat this parameter tensor to our inputs, defined in [line 225](https://github.com/SamsungLabs/Multitask-RFG/blob/main/mtrfg/parser/biaffine_dependency_parser.py#L225)?

```
encoded_text_input = torch.cat([encoded_text_input, tag_embeddings], -1)
```

Thank you very much in advance for the help!

**Comment by dhaivat1729** [comment]
Hi @paolo-gajo 

Thank you for your interest in your work. Here are some clarifications: 

1. Yes, for the baseline, what we are using is identical to what Donatelli et al. is using. We had tried multi layered module there too [in this line](https://github.com/SamsungLabs/Multitask-RFG/blob/main/mtrfg/parser/biaffine_dependency_parser.py#L151).  However, we eventually found that increasing number of layers to build dense tag representation is not improving performance. So we decided to go with just 1 layer, which is similar to embedding layer. This also ensures that we do not increase number of parameters in the model and compute time. 


2. This is standard part of Biaffine parsing pipeline, that we haven't touched. We borrowed the code [from here.](https://docs.allennlp.org/v0.9.0/api/allennlp.models.biaffine_dependency_parser.html). You can probably raise a question for them. 


3. The concatenation we are doing in [line 225](
https://github.com/SamsungLabs/Multitask-RFG/blob/main/mtrfg/parser/biaffine_dependency_parser.py#L225), is just merging tag representation and recipe text representation. This is also present in our this part of the diagram,


![Screenshot 2024-08-02 at 2 23 52 PM](https://github.com/user-attachments/assets/1a60e9ed-f3e8-4521-9a43-c04385bc9fe3)

I hope this answers your questions. I suggest that you put breakpoints around [these lines](https://github.com/SamsungLabs/Multitask-RFG/blob/main/mtrfg/parser/biaffine_dependency_parser.py#L232) to understand. I remember checking it when I used it, however I do not recall its exact purpose right now. 

Feel free to ask any clarifying questions.

**Comment by dhaivat1729** [comment]
Closing the issue now. Feel free to open if anything is not clear.
